Repository wecode-bootcamp-korea/18-2nd-mukbang-frontend, pull requests merged in 2021-04, with the labels that each got.

#3 [18기 배성훈] 가게리스트 레이아웃 완성 및 1차 기능구현 완료
  .eslintrc.json
  package-lock.json
  package.json
  public/data/data0.json
  public/data/data1.json
  public/data/data2.json
  src/Components/Header/Header.js
  src/Pages/Main/Components/StoreList/StoreList.js
  src/Pages/Main/Components/StoreList/StoreList.scss
  src/Pages/Main/Main.scss
  src/Styles/GlobalStyle.js
  src/Styles/common.scss
  src/index.js
  yarn.lock
Labels: Status: 리뷰 요청

#5 [18기 송나은] StoreDetail 레이아웃 완료 (Map, Roadview API 포함)
  .eslintrc.json
  package-lock.json
  package.json
  public/data/menu.json
  public/data/storeDetail.json
  public/index.html
  src/Pages/Main/Components/StoreDetail/ImageSlider.js
  src/Pages/Main/Components/StoreDetail/Info.js
  src/Pages/Main/Components/StoreDetail/Map.js
  src/Pages/Main/Components/StoreDetail/Menu.js
  src/Pages/Main/Components/StoreDetail/Modal.js
  src/Pages/Main/Components/StoreDetail/Preview.js
  src/Pages/Main/Components/StoreDetail/Review.js
  src/Pages/Main/Components/StoreDetail/ReviewImg.js
  src/Pages/Main/Components/StoreDetail/Roadview.js
  src/Pages/Main/Components/StoreDetail/StoreDetail.js
  src/Pages/Main/Components/StoreDetail/StoreDetail.scss
  src/Pages/Main/Components/StoreDetail/StoreInfo.js
  src/Pages/Main/Main.js
  src/Styles/GlobalStyle.js
Labels: Status: 리뷰 요청

#6 [18기 정승옥] 헤더 레이아웃, hover, link path 작업
  package-lock.json
  package.json
  public/index.html
  src/Components/Header/Components/SearchList/SearchList.js
  src/Components/Header/Header.js
  src/Components/Header/Header.scss
  src/Components/Header/images/logo.png
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Routes.js
  yarn.lock
Labels: Status: 리뷰 요청

#7 [18기 정승옥] 리뷰 반영 완료
  package-lock.json
  package.json
  public/index.html
  src/Components/Header/Header.js
  src/Pages/Register/DetailInfo/DetailInfo.js
  src/Pages/Register/ImageInfo/ImageInfo.js
  src/Pages/Register/MenuInfo/MenuInfo.js
  src/Pages/Register/Register.js
  src/Pages/Register/RegisterAddress/RegisterAddress.js
  src/Pages/Register/RegisterMenu/RegisterMenu.js
  src/Pages/Register/RegisterStoreImage/RegisterStoreImage.js
  src/Pages/Register/StoreDetail/StoreDetail.js
  src/Pages/Register/StyleData/StyleData.js
  src/Pages/Register/images/adBanner1.png
  src/Pages/Register/images/adBanner2.png
  src/Pages/Register/images/topBanner.png
  src/Routes.js
  yarn.lock
Labels: Status: 리뷰 요청

#9 [18기 송나은] 리뷰 등록하기 모달창 기능 구현 완료
  src/Pages/Main/Components/StoreDetail/Info.js
  src/Pages/Main/Components/StoreDetail/Modal.js
  src/Pages/Main/Components/StoreDetail/Review.js
Labels: Status: Accepted

#10 [18기 송나은] StoreDetail. StoreList 이동기능 구현 완료
  package-lock.json
  src/Components/Header/Header.js
  src/Pages/Main/Components/StoreDetail/Info.js
  src/Pages/Main/Components/StoreDetail/Map.js
  src/Pages/Main/Components/StoreDetail/Modal.js
  src/Pages/Main/Components/StoreDetail/Preview.js
  src/Pages/Main/Components/StoreDetail/Review.js
  src/Pages/Main/Components/StoreDetail/StoreDetail.js
  src/Pages/Main/Components/StoreList/StoreList.js
  src/Pages/Main/Main.js
  src/Routes.js
Labels: Status: 리뷰 진행 중

#2 [18기 정승옥] 카카오 지도 마커 중복 오류 개선
  package-lock.json
  package.json
  public/data/Markers.json
  public/index.html
  src/Components/Header/Header.js
  src/Pages/Main/Components/Filter/Filter.js
  src/Pages/Main/Components/Filter/Filter.scss
  src/Pages/Main/Components/FoodMap/CreateMapMarks.js
  src/Pages/Main/Components/FoodMap/Filter/Filter.js
  src/Pages/Main/Components/FoodMap/Filter/Images/Filter.png
  src/Pages/Main/Components/FoodMap/Filter/OptionStyled/OptionStyled.js
  src/Pages/Main/Components/FoodMap/Filter/PriceCategoryContext.js
  src/Pages/Main/Components/FoodMap/Filter/PriceOption/PriceOption.js
  src/Pages/Main/Components/FoodMap/Filter/StoreOption/StoreOption.js
  src/Pages/Main/Components/FoodMap/FoodMap.js
  src/Pages/Main/Components/FoodMap/FoodMap.scss
  src/Pages/Main/Components/FoodMap/images/bread.png
  src/Pages/Main/Components/FoodMap/images/chicken.png
  src/Pages/Main/Components/FoodMap/images/chinese.png
  src/Pages/Main/Components/FoodMap/images/coffee.png
  src/Pages/Main/Components/FoodMap/images/fastfood.png
  src/Pages/Main/Components/FoodMap/images/fusion.png
  src/Pages/Main/Components/FoodMap/images/korean.png
  src/Pages/Main/Components/FoodMap/images/snack.png
  src/Pages/Main/Components/FoodMap/images/sushi.png
  src/Pages/Main/Components/FoodMap/images/west.png
  src/Pages/Main/Components/StoreList/StoreList.js
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Styles/GlobalStyle.js
  yarn.lock
Labels: Status: 리뷰 요청

#8 [18기 배성훈] 로그인 및 회원가입 레이아웃 및 기능구현
  eState } from react
  package-lock.json
  public/index.html
  src/Components/Header/Header.js
  src/Pages/Login/Components/common/common.js
  src/Pages/Login/Components/common/formlayout.js
  src/Pages/Login/Components/common/logoBox.js
  src/Pages/Login/Components/emailForm.js
  src/Pages/Login/Components/loginForm.js
  src/Pages/Login/Components/signupForm.js
  src/Pages/Login/Login.js
  src/Pages/Login/email.js
  src/Pages/Login/signup.js
  src/Pages/Main/Components/StoreList/StoreList.js
  src/Pages/Main/Login/Login.js
  src/Pages/Main/Login/Login.scss
  src/Routes.js
  src/Styles/GlobalStyle.js
  src/Styles/common.scss
  src/index.js
  yarn.lock
Labels: Status: 리뷰 요청

#11 [18기 정승옥] 홈 검색 컴포넌트 레이아웃, CSS 작업 완료
  package-lock.json
  src/Pages/Home/Home.js
  src/Pages/Home/images/Salad.jpeg
  src/Pages/Home/images/banana.jpeg
  src/Pages/Home/images/fusion.jpeg
  src/Pages/Home/images/home_banner1.jpeg
  src/Pages/Home/images/pear.jpeg
  src/Pages/Home/images/phone_banner.png
  src/Pages/Home/images/search_icon.png
  src/Pages/Home/images/select.png
  src/Pages/Home/images/slide_img1.jpeg
  src/Pages/Home/images/wecode.jpeg
  src/Pages/Main/Components/FoodMap/FoodMap.js
  src/Pages/Main/Components/StoreDetail/StoreDetail.js
  src/Routes.js
  yarn.lock
Labels: Status: 리뷰 요청

#12 [18기 배성훈] 가게 리스트 2차기능 구현 중
  src/Components/Header/images/Logo.jpg
  src/Image/logo.jpg
  src/Pages/Login/Components/common/logoBox.js
  src/Pages/Login/Login.js
  src/Pages/Main/Components/FoodMap/FoodMap.js
  src/Pages/Main/Components/StoreDetail/StoreDetail.js
  src/Pages/Main/Components/StoreList/StoreList.js
Labels: Status: 리뷰 요청

#15 [18기 배성훈] 가게리스트 최종 기능구현 완료
  src/Pages/Login/headerHidden.js
  src/Pages/Main/Components/StoreList/StoreList.js
  src/Routes.js
Labels: Status: 리뷰 요청
